In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [3]:
data={"color":["Red" , "Green", "Yellow", "orange","pink"]}
df=pd.DataFrame(data)
df

    color
0     Red
1   Green
2  Yellow
3  orange
4    pink

In [5]:
label_encoder=LabelEncoder()
df['Color_label']=label_encoder.fit_transform(df['color'])
df.head()

    color  Color_label
0     Red            1
1   Green            0
2  Yellow            2
3  orange            3
4    pink            4

In [7]:
one_hot_encoder=OneHotEncoder()
one_hot_encoded=one_hot_encoder.fit_transform(df[['color']])
one_hot_encoded_df=pd.DataFrame(one_hot_encoded.toarray(),columns=one_hot_encoder.get_feature_names_out())
df=pd.concat([df,one_hot_encoded_df],axis=1)
df

,color,Color_label,color_Green,color_Red,color_Yellow,color_orange,color_pink
0,Red,1,0.0,1.0,0.0,0.0,0.0
1,Green,0,1.0,0.0,0.0,0.0,0.0
2,Yellow,2,0.0,0.0,1.0,0.0,0.0
3,orange,3,0.0,0.0,0.0,1.0,0.0
4,pink,4,0.0,0.0,0.0,0.0,1.0