In [3]:
import pandas as pd

df = pd.read_csv('Day_11_banking_data.csv')

sorted_df = df.sort_values(by='Account_Balance', ascending=False).head(10)
sorted_df

,Date,Account_Type,Branch,Transaction_Type,Transaction_Amount,Account_Balance
15,2023-01-03,Savings,Suburban,Service Charge,3350.32,12836.51
8,2023-01-20,Recurring Deposit,Downtown,Service Charge,3899.98,12646.56
2,2023-01-10,Current,Uptown,Loan Payment,3363.85,12428.67
7,2023-01-09,Current,Central,Loan Payment,2346.72,10708.85
17,2023-01-07,Current,Central,Loan Payment,4116.52,9785.64
1,2023-01-16,Current,Uptown,Withdrawal,641.43,8908.39
19,2023-01-17,Savings,Central,Deposit,4516.52,8789.19
18,2023-01-12,Recurring Deposit,Suburban,Service Charge,1339.57,8666.74
16,2023-01-02,Fixed Deposit,Central,Deposit,4421.57,8330.40
14,2023-01-01,Fixed Deposit,Downtown,Withdrawal,4136.54,8175.08

In [4]:
df['Transaction_Rank'] = df.groupby('Branch')['Transaction_Amount'].rank(ascending=False)
df

,Date,Account_Type,Branch,Transaction_Type,Transaction_Amount,Account_Balance,Transaction_Rank
0,2023-01-19,Fixed Deposit,Central,Loan Payment,985.51,6839.59,7.0
1,2023-01-16,Current,Uptown,Withdrawal,641.43,8908.39,4.0
2,2023-01-10,Current,Uptown,Loan Payment,3363.85,12428.67,1.0
3,2023-01-18,Savings,Uptown,Loan Payment,1914.60,5776.63,2.0
4,2023-01-14,Recurring Deposit,Suburban,Loan Payment,2788.57,4779.04,3.0
5,2023-01-06,Current,Suburban,Service Charge,4584.05,7635.47,1.0
6,2023-01-04,Recurring Deposit,Central,Service Charge,1621.82,6465.79,6.0
7,2023-01-09,Current,Central,Loan Payment,2346.72,10708.85,5.0
8,2023-01-20,Recurring Deposit,Downtown,Service Charge,3899.98,12646.56,2.0
9,2023-01-11,Fixed Deposit,Downtown,Deposit,1529.59,2592.16,3.0
10,2023-01-13,Recurring Deposit,Central,Deposit,846.41,6443.14,8.0
11,2023-01-08,Fixed Deposit,Suburban,Service Charge,1803.88,6560.58,4.0
12,2023-01-15,Fixed Deposit,Uptown,Service Charge,1225.50,4224.47,3.0
13,2023-01-05,Recurring Deposit,Central,Loan Payment,4683.64,6762.43,1.0
14,2023-01-01,Fixed Deposit,Downtown,Withdrawal,4136.54,8175.08,1.0
15,2023-01-03,Savings,Suburban,Service Charge,3350.32,12836.51,2.0
16,2023-01-02,Fixed Deposit,Central,Deposit,4421.57,8330.40,3.0
17,2023-01-07,Current,Central,Loan Payment,4116.52,9785.64,4.0
18,2023-01-12,Recurring Deposit,Suburban,Service Charge,1339.57,8666.74,5.0
19,2023-01-17,Savings,Central,Deposit,4516.52,8789.19,2.0