In [2]:
import pandas as pd

df = pd.read_csv('Day_10_banking_data.csv')

filtered_transactions = df[df['Transaction_Amount'] > 2000]
print(filtered_transactions)

loan_payments = df[(df['Transaction_Type'] == 'Loan Payment') & (df['Account_Balance'] > 5000)]
print(loan_payments)

uptown_transactions = df[df['Branch'] == 'Uptown']
print(uptown_transactions)

          Date       Account_Type    Branch Transaction_Type  \
2   2023-01-10            Current    Uptown     Loan Payment
4   2023-01-14  Recurring Deposit  Suburban     Loan Payment
5   2023-01-06            Current  Suburban   Service Charge
7   2023-01-09            Current   Central     Loan Payment
8   2023-01-20  Recurring Deposit  Downtown   Service Charge
13  2023-01-05  Recurring Deposit   Central     Loan Payment
14  2023-01-01      Fixed Deposit  Downtown       Withdrawal
15  2023-01-03            Savings  Suburban   Service Charge
16  2023-01-02      Fixed Deposit   Central          Deposit
17  2023-01-07            Current   Central     Loan Payment
19  2023-01-17            Savings   Central          Deposit

    Transaction_Amount  Account_Balance
2              3363.85         12428.67
4              2788.57          4779.04
5              4584.05          7635.47
7              2346.72         10708.85
8              3899.98         12646.56
13             4683.64          6762.43
14             4136.54          8175.08
15             3350.32         12836.51
16             4421.57          8330.40
17             4116.52          9785.64
19             4516.52          8789.19
          Date       Account_Type   Branch Transaction_Type  \
0   2023-01-19      Fixed Deposit  Central     Loan Payment
2   2023-01-10            Current   Uptown     Loan Payment
3   2023-01-18            Savings   Uptown     Loan Payment
7   2023-01-09            Current  Central     Loan Payment
13  2023-01-05  Recurring Deposit  Central     Loan Payment
17  2023-01-07            Current  Central     Loan Payment

    Transaction_Amount  Account_Balance
0               985.51          6839.59
2              3363.85         12428.67
3              1914.60          5776.63
7              2346.72         10708.85
13             4683.64          6762.43
17             4116.52          9785.64
          Date   Account_Type  Branch Transaction_Type  Transaction_Amount  \
1   2023-01-16        Current  Uptown       Withdrawal              641.43
2   2023-01-10        Current  Uptown     Loan Payment             3363.85
3   2023-01-18        Savings  Uptown     Loan Payment             1914.60
12  2023-01-15  Fixed Deposit  Uptown   Service Charge             1225.50

    Account_Balance
1           8908.39
2          12428.67
3           5776.63
12          4224.47

In [3]:
df['Transaction_Fee'] = df['Transaction_Amount'] * 0.02
df['Balance_Status'] = df['Account_Balance'].apply(lambda x: 'High Balance' if x > 5000 else 'Low Balance')
df

,Date,Account_Type,Branch,Transaction_Type,Transaction_Amount,Account_Balance,Transaction_Fee,Balance_Status
0,2023-01-19,Fixed Deposit,Central,Loan Payment,985.51,6839.59,19.7102,High Balance
1,2023-01-16,Current,Uptown,Withdrawal,641.43,8908.39,12.8286,High Balance
2,2023-01-10,Current,Uptown,Loan Payment,3363.85,12428.67,67.2770,High Balance
3,2023-01-18,Savings,Uptown,Loan Payment,1914.60,5776.63,38.2920,High Balance
4,2023-01-14,Recurring Deposit,Suburban,Loan Payment,2788.57,4779.04,55.7714,Low Balance
5,2023-01-06,Current,Suburban,Service Charge,4584.05,7635.47,91.6810,High Balance
6,2023-01-04,Recurring Deposit,Central,Service Charge,1621.82,6465.79,32.4364,High Balance
7,2023-01-09,Current,Central,Loan Payment,2346.72,10708.85,46.9344,High Balance
8,2023-01-20,Recurring Deposit,Downtown,Service Charge,3899.98,12646.56,77.9996,High Balance
9,2023-01-11,Fixed Deposit,Downtown,Deposit,1529.59,2592.16,30.5918,Low Balance
10,2023-01-13,Recurring Deposit,Central,Deposit,846.41,6443.14,16.9282,High Balance
11,2023-01-08,Fixed Deposit,Suburban,Service Charge,1803.88,6560.58,36.0776,High Balance
12,2023-01-15,Fixed Deposit,Uptown,Service Charge,1225.50,4224.47,24.5100,Low Balance
13,2023-01-05,Recurring Deposit,Central,Loan Payment,4683.64,6762.43,93.6728,High Balance
14,2023-01-01,Fixed Deposit,Downtown,Withdrawal,4136.54,8175.08,82.7308,High Balance
15,2023-01-03,Savings,Suburban,Service Charge,3350.32,12836.51,67.0064,High Balance
16,2023-01-02,Fixed Deposit,Central,Deposit,4421.57,8330.40,88.4314,High Balance
17,2023-01-07,Current,Central,Loan Payment,4116.52,9785.64,82.3304,High Balance
18,2023-01-12,Recurring Deposit,Suburban,Service Charge,1339.57,8666.74,26.7914,High Balance
19,2023-01-17,Savings,Central,Deposit,4516.52,8789.19,90.3304,High Balance